services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: saelt-app
    container_name: saelt-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - saelt-network
    depends_on:
      - db

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: saelt-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - saelt-network
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: saelt-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-saelt}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-saelt}
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3307:3306"
    networks:
      - saelt-network

  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: saelt-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    networks:
      - saelt-network
    depends_on:
      - db

# Docker Networks
networks:
  saelt-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
